name: Tests
on: [push, pull_request]

jobs:
  test:
    name: Build & test
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build
        run: dub build

      - name: Run tests
        run: dub test
